[program:horizon]
command=php /var/www/kalibrium/artisan horizon
directory=/var/www/kalibrium
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/horizon.log
stopwaitsecs=3600
stopasgroup=true
killasgroup=true
