#!/usr/bin/env bash
# ============================================================================
# install-git-hooks.sh — Instalador idempotente de hooks git nativos
#
# Slice: 019 (AC-001, AC-003, AC-004)
# Plan:  specs/019/plan.md  D-01, D-04
# Spec:  specs/019/spec.md   AC-001
#
# Objetivo: criar `.git/hooks/pre-push` que invoca
# `scripts/pre-push-native.sh`, cobrindo pushers FORA do Claude Code
# (PM via .bat, workflow_dispatch, outra sessao sem PreToolUse).
# Complementa (nao substitui) o hook PreToolUse `pre-push-gate.sh`.
#
# Contrato:
#   - 1a execucao: cria `.git/hooks/pre-push`, imprime:
#       installed: .git/hooks/pre-push
#   - 2a execucao (hook ja atualizado): imprime:
#       already-current: .git/hooks/pre-push
#   - Flag `--silent`: suprime stdout (mantem stderr para erros reais).
#
# Idempotencia: conteudo do wrapper e FIXO (heredoc + LF explicito). SHA-256
# entre execucoes 1 e 2 e identico. Forca LF para blindar contra CRLF do
# Windows (R-03 do plan).
#
# Autor: builder (modo implementer), slice-019.
# ============================================================================

set -euo pipefail

# Root do repositorio (sobrevive a invocacao de qualquer cwd)
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd)"

HOOK_DIR="${REPO_ROOT}/.git/hooks"
HOOK_PATH="${HOOK_DIR}/pre-push"
NATIVE_SCRIPT_REL="scripts/pre-push-native.sh"

SILENT=0
for arg in "$@"; do
  case "$arg" in
    --silent) SILENT=1 ;;
    *) ;;  # flags adicionais reservadas para futuro
  esac
done

log() {
  if [ "$SILENT" -eq 0 ]; then
    printf '%s\n' "$*"
  fi
}

# --------------------------------------------------------------------------
# 1. Verifica pre-condicoes (dentro de repo git, com .git/)
# --------------------------------------------------------------------------
if [ ! -d "${REPO_ROOT}/.git" ]; then
  printf 'error: not inside a git repository (%s/.git missing)\n' "${REPO_ROOT}" >&2
  exit 1
fi

# Cria .git/hooks/ se nao existir (repos recem-clonados ja tem, mas defensivo)
if [ ! -d "${HOOK_DIR}" ]; then
  mkdir -p "${HOOK_DIR}"
fi

# --------------------------------------------------------------------------
# 2. Gera conteudo canonico do wrapper (idempotente — string fixa com LF).
#    Usa printf com \n explicito para evitar autocrlf do Windows.
# --------------------------------------------------------------------------
WRAPPER_CONTENT="$(printf '#!/usr/bin/env bash\n# Auto-generated by scripts/install-git-hooks.sh (slice-019).\n# Wrapper nativo do git pre-push: delega para scripts/pre-push-native.sh.\n# Cobre pushers externos ao Claude Code (PM via .bat, workflow_dispatch, etc.).\n# Nao editar manualmente — regerado pelo installer em cada SessionStart.\nset -e\nREPO_ROOT="$(git rev-parse --show-toplevel)"\nexec bash "${REPO_ROOT}/%s" "$@"\n' "${NATIVE_SCRIPT_REL}")"

# --------------------------------------------------------------------------
# 3. Compara com hook existente
# --------------------------------------------------------------------------
NEED_WRITE=1
if [ -f "${HOOK_PATH}" ]; then
  EXISTING="$(cat "${HOOK_PATH}" 2>/dev/null || printf '')"
  if [ "$EXISTING" = "$WRAPPER_CONTENT" ]; then
    NEED_WRITE=0
  fi
fi

# --------------------------------------------------------------------------
# 4. Escreve (ou anuncia already-current)
# --------------------------------------------------------------------------
if [ "$NEED_WRITE" -eq 1 ]; then
  # Escrita via printf garante LF; diretorio .git/ nao sofre autocrlf.
  printf '%s' "$WRAPPER_CONTENT" > "${HOOK_PATH}"
  chmod +x "${HOOK_PATH}"
  log "installed: .git/hooks/pre-push"
else
  log "already-current: .git/hooks/pre-push"
fi

exit 0
